### ISSUE TITLE
Syntax highlighting issue

### ISSUE THREAD

**Issue by ajmichaels** [oivva/sublime-file-icons#54]
There are some issues with the built in syntax themes that the icons package provides.  For instance, I can't use comments in a webpack file without messing up the syntax highlighting:

![image](https://cloud.githubusercontent.com/assets/14307368/20329028/f07e9c20-ab63-11e6-9b0c-0c4fdd2deaf5.png)

Further, I've tried to tell sublime to "open all with current extension as" using the babel package, but it keeps going back to the webpack syntax built in with the icons package.  Is there a way to disable/remove the syntax themes bundled with the icons package?

**Comment by r3nya** [comment]
Hey @ajmichaels!

Thanks for your report. I will look it soon.

**Comment by oivva** [comment]
@ajmichaels Could you provide me your `webpack.config.js`?

**Comment by ajmichaels** [comment]
@oivva https://dpaste.de/COVg

**Comment by oivva** [comment]
Please also provide this command output

![](http://i.imgur.com/qzd2oWi.png)

**Comment by ajmichaels** [comment]
@oivva not sure exactly what you mean, but http://imgur.com/a/BW3NU

**Comment by ajmichaels** [comment]
@oivva the output from environment is:
 - File Icons: 2.1.0
- Sublime Text: 3126
- Platform: osx
- Package Control: True
- Current Theme: Boxy Ocean.sublime-theme
- Installed Themes: {'Boxy Theme': ['Boxy Monokai.sublime-theme', 'Boxy Nova.sublime-theme', 'Boxy Ocean.sublime-theme', 'Boxy Solarized Dark.sublime-theme', 'Boxy Solarized Light.sublime-theme', 'Boxy Tomorrow.sublime-theme', 'Boxy Yesterday.sublime-theme'], 'Theme - Default': ['Default.sublime-theme'], 'themes': ['Material Augmented Reaction.sublime-theme', 'Material Behave.sublime-theme', 'Material Brogrammer.sublime-theme', 'Material Cobalt.sublime-theme', 'Material Dracula.sublime-theme', 'Material Facebook.sublime-theme', 'Material Firewatch.sublime-theme', 'Material Flatland.sublime-theme', 'Material Glacier.sublime-theme', 'Material Monokai Soda.sublime-theme', 'Material Monokai.sublime-theme', 'Material Oceanic Next.sublime-theme', 'Material One Dark.sublime-theme', 'Material Primer Light.sublime-theme', 'Material Seti.sublime-theme', 'Material Solarized Dark.sublime-theme', 'Material Solarized Light.sublime-theme', 'Material Spaceblack.sublime-theme', 'Material Spacegray Eighties.sublime-theme', 'Material Spacegray Light.sublime-theme', 'Material Spacegray Mocha.sublime-theme', 'Material Spacegray.sublime-theme', 'Material Stereokai.sublime-theme', 'Material Toy Chest.sublime-theme', 'Material Twilight.sublime-theme', 'Material Vim Blackboard.sublime-theme', 'Material Zenburn.sublime-theme']}

**Comment by oivva** [comment]
@ajmichaels Thanks! Now I've found the way how to reproduce the bug.

**Comment by oivva** [comment]
Ok, after some investigations I can say that this bug related to the [Babel](https://github.com/babel/babel-sublime) package. I can reproduce it only when the default JS syntax is disabled and Babel is installed. In your case better to use [this instructions](https://github.com/babel/babel-sublime#setting-as-the-default-syntax) but not disable default syntax.

If you want to use babel and don't need icons for e.g. `webpack.config.js` you can use one of these steps:

* Create in your `Packages/User` folder `JavaScript (Babel).sublime-settings` file with this contents:

```json
{
	"extensions":
	[
		"js",
		"webpack.config.js"
	]
}
```

* Enable default `JavaScript` package

* Remove aliases which you don't need from the `Packages/zz File Icons/dist/languages`. However I'll add option to the plugin settings to disable all aliases in 2.1.1.

**Comment by ChainsawBaby** [comment]
@ihodev I was just to create a pull request, but I see it's a known issue.
The problem lies with comments, so if you add this to the javascript aliases, it works fine.
I have added this to the gulpfile syntax locally, and I now get no issues.

I haven't testet with the others, as I have no files to test them on.
```yaml
  prototype:
    - include: comments
  comments:
    - match: /\*\*(?!/)
      scope: punctuation.definition.comment.js
      push:
        - meta_scope: comment.block.documentation.js
        - match: \*/
          scope: punctuation.definition.comment.js
          pop: true

    - match: /\*
      scope: punctuation.definition.comment.begin.js
      push:
        - meta_scope: comment.block.js
        - match: \*/
          scope: punctuation.definition.comment.end.js
          pop: true

    - match: //
      scope: punctuation.definition.comment.js
      push:
        - meta_scope: comment.line.double-slash.js
        - match: $\n?
          pop: true
```

I copied that from the Javascript syntax from the Babel package
